/*
 * Copyright (c) 2026-present, the Ladybird developers.
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

// Prints the expectation tables of the numeric conversion tests, computed by the C++ runtime. Run it through
// regenerate.sh, which splits the output into one file per "//// FILE:" marker.

"use strict";

// The committed tables use a scale of 1. A larger scale and another seed give a wider sweep for local checks.
const SCALE = 1;
const scaled = count => count * SCALE;

let seed = 0x2545f491;
function nextU32() {
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return (t ^ (t >>> 14)) >>> 0;
}
const randomInt = n => nextU32() % n;
const pick = array => array[randomInt(array.length)];
const randomSign = () => (randomInt(2) ? -1 : 1);

const float64 = new Float64Array(1);
const uint64 = new BigUint64Array(float64.buffer);
function bitsOf(x) {
    float64[0] = x;
    return "0x" + uint64[0].toString(16).padStart(16, "0");
}
function fromBits(bits) {
    uint64[0] = bits;
    return float64[0];
}
function nextDouble(x, direction) {
    if (x === 0) return direction > 0 ? Number.MIN_VALUE : -Number.MIN_VALUE;
    float64[0] = x;
    uint64[0] += direction > 0 === x >= 0 ? 1n : -1n;
    return float64[0];
}
function randomFiniteDouble() {
    for (;;) {
        const x = fromBits((BigInt(nextU32()) << 32n) | BigInt(nextU32()));
        if (Number.isFinite(x)) return x;
    }
}
function randomDoubleWithExponent(minimum, maximum) {
    const exponent = minimum + randomInt(maximum - minimum + 1);
    const mantissa = (BigInt(nextU32() & 0xfffff) << 32n) | BigInt(nextU32());
    return randomSign() * fromBits((BigInt(exponent + 1023) << 52n) | mantissa);
}
function randomShortDecimal() {
    const digits = 1 + randomInt(9);
    let integer = 0;
    for (let i = 0; i < digits; ++i) integer = integer * 10 + randomInt(10);
    return (randomSign() * integer) / 10 ** randomInt(digits + 3);
}
function randomDigits(count, alphabet = "0123456789") {
    let text = "";
    for (let i = 0; i < count; ++i) text += pick(alphabet);
    return text;
}
function randomBigInt(maximumBits) {
    const bits = randomInt(maximumBits + 1);
    let value = 0n;
    for (let i = 0; i < bits; i += 32) value = (value << 32n) | BigInt(nextU32());
    value &= (1n << BigInt(bits)) - 1n;
    return randomInt(2) ? -value : value;
}

function rustString(text) {
    let result = '"';
    for (const character of text) {
        const codePoint = character.codePointAt(0);
        if (character === '"' || character === "\\") result += "\\" + character;
        else if (codePoint >= 0x20 && codePoint < 0x7f) result += character;
        else result += "\\u{" + codePoint.toString(16) + "}";
    }
    return result + '"';
}
const rustOption = (value, format) => (value === null || value === undefined ? "None" : `Some(${format(value)})`);
const describeError = error => `${error.name}: ${error.message}`;
function attempt(operation) {
    try {
        return operation();
    } catch (error) {
        return describeError(error);
    }
}

function printTableHeader() {
    print("/*");
    print(" * Copyright (c) 2026-present, the Ladybird developers.");
    print(" *");
    print(" * SPDX-License-Identifier: BSD-2-Clause");
    print(" */");
    print("");
    print("// Generated by generate.js, which runs on the C++ js binary. Regenerate with regenerate.sh.");
}

function emitTable(name, type, rows) {
    const rowTypeName =
        name.toLowerCase().replace(/(^|_)([a-z])/g, (match, separator, letter) => letter.toUpperCase()) + "Row";
    print(`type ${rowTypeName} = ${type.replaceAll("&", "&'static ")};`);
    print(`const ${name}: &[${rowTypeName}] = &[`);
    for (const row of rows) print(`    (${row.join(", ")}),`);
    print("];");
}

const interestingDoubles = [
    0,
    -0,
    1,
    -1,
    0.5,
    -0.5,
    1.5,
    -1.5,
    2.5,
    -2.5,
    0.1,
    0.2,
    0.3,
    1 / 3,
    2 / 3,
    123.456,
    -123.456,
    1e21,
    -1e21,
    1e-7,
    1e-6,
    5e-324,
    -5e-324,
    1e-323,
    2.2250738585072014e-308,
    2.225073858507201e-308,
    Number.MAX_VALUE,
    -Number.MAX_VALUE,
    2 ** 31,
    2 ** 31 - 1,
    -(2 ** 31),
    -(2 ** 31) - 1,
    2 ** 32,
    2 ** 32 + 1,
    -(2 ** 32),
    2 ** 53,
    2 ** 53 + 2,
    -(2 ** 53),
    2 ** 64,
    2 ** 64 + 2 ** 12,
    1e300,
    -1e300,
    9.995,
    1.005,
    1.45,
    4.35,
    8.345,
    0.045,
    1e23,
    2 ** -20,
    2 ** -1022,
    2 ** -1074,
    0.49999999999999994,
    254.5,
    255.5,
    253.5,
    255,
    256,
    65535.5,
    65536,
    32767.5,
    32768,
    127.5,
    128,
    -128.5,
    2 ** 50 + 0.25,
    2 ** 50 + 0.75,
    2 ** 51 + 0.5,
    2 ** 52 + 1,
    2 ** 52 - 0.5,
    999999999999999999999,
    1e15 + 0.3,
    123456789012345680000,
    0.000001234,
    4294967295.5,
    4294967296.5,
    -4294967296.5,
    1e-10,
    7e-10,
    1.7976931348623157e308,
    Math.PI,
    Math.E,
    -Math.PI,
    2 ** 1023,
    2 ** -1023,
    3 * 2 ** -1074,
    0.1 + 0.2,
];

function randomDoubles(count) {
    const values = [];
    for (let i = 0; i < count; ++i) {
        switch (randomInt(6)) {
            case 0:
                values.push(randomFiniteDouble());
                break;
            case 1:
                values.push(randomDoubleWithExponent(-30, 80));
                break;
            case 2:
                values.push(randomShortDecimal());
                break;
            case 3:
                values.push(randomSign() * (nextU32() * 2 ** randomInt(40) + randomInt(4) / 4));
                break;
            case 4:
                values.push(randomDoubleWithExponent(-1074 + 52, -1000));
                break;
            default:
                values.push(randomSign() * 2 ** (randomInt(2098) - 1074));
        }
    }
    return values;
}

// value_conversions_table.rs

function stringToNumberInputs() {
    const inputs = [
        "",
        " ",
        "\t\n\v\f\r",
        "0",
        "-0",
        "+0",
        "  12  ",
        "1e3",
        "1E3",
        "1e+3",
        "1e-3",
        ".5",
        "5.",
        ".",
        "+",
        "-",
        "e",
        "1e",
        "1e+",
        "1e-",
        "1.2.3",
        "1..2",
        "Infinity",
        "+Infinity",
        "-Infinity",
        "infinity",
        "INFINITY",
        "Infinityx",
        " Infinity ",
        " -Infinity　",
        "+-1",
        "--1",
        "++1",
        "0x10",
        "0X1f",
        "0x",
        "0X",
        "0xg",
        "-0x10",
        "+0x10",
        "0b101",
        "0B11",
        "0b2",
        "0b",
        "0o17",
        "0O17",
        "0o8",
        "0o",
        "00x10",
        "0x1_0",
        "1_000",
        "1,000",
        "١",
        "１",
        "0.1",
        "0.30000000000000004",
        "9007199254740993",
        "9007199254740993.0000000000000001",
        "1.7976931348623157e308",
        "1.7976931348623158e308",
        "1.797693134862315807e308",
        "1.7976931348623159e308",
        "1e309",
        "-1e309",
        "4.9e-324",
        "2.4703282292062327e-324",
        "2.4703282292062328e-324",
        "1e-400",
        "-1e-400",
        "0x1fffffffffffff",
        "0x20000000000001",
        "0x20000000000003",
        "0x20000000000002",
        "0xfffffffffffffc00",
        "0xfffffffffffffbff",
        "0xfffffffffffffc01",
        "0x" + "f".repeat(256),
        "0x" + "f".repeat(255) + "7",
        "0x1" + "0".repeat(255),
        "0b" + "1".repeat(60),
        "0b1" + "0".repeat(52) + "1",
        "0o" + "7".repeat(30),
        "1" + "0".repeat(400),
        "0." + "0".repeat(400) + "1",
        "123456789012345678901234567890",
        "1e1000000000000000000000",
        "0e1000000000000000000000",
        "-0e5",
        ".e1",
        "1.e1",
        "-.5e-3",
        "+.5",
        "12abc",
        "5\u0000",
        "᠎5",
        "5​",
        "\u00855",
        "0.0000001",
        "1e-7",
        "1E-7",
        "00012",
        "0000.5000",
        "-0.0",
        "1😀5",
        "😀",
        "0x١",
        "0e",
        "0e0",
        "0e-0",
        "-00",
        "1e+0010",
        "123.456e-2",
        "9".repeat(800),
        "0." + "9".repeat(800),
        "1" + "e-325",
    ];
    for (const whitespace of [
        "\u0009",
        "\u000a",
        "\u000b",
        "\u000c",
        "\u000d",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        "　",
        "﻿",
    ]) {
        inputs.push(whitespace + "5" + whitespace, whitespace + "0x1a", "-7" + whitespace, "1" + whitespace + "2");
    }

    // 2^-1075, the midpoint between +0 and the smallest subnormal, followed by its neighbours.
    const smallestSubnormalMidpoint = "0." + (5n ** 1075n).toString().padStart(1075, "0");
    inputs.push(
        smallestSubnormalMidpoint,
        smallestSubnormalMidpoint + "1",
        smallestSubnormalMidpoint.slice(0, -1) + "4"
    );

    // The midpoint between the largest double and 2^1024, which rounds to infinity, and just below it.
    const overflowMidpoint = (2n ** 1024n - 2n ** 970n).toString();
    inputs.push(overflowMidpoint, overflowMidpoint.slice(0, -1) + "4", overflowMidpoint + ".000000000000001");

    for (let i = 0; i < scaled(120); ++i) {
        const x = pick([randomFiniteDouble, () => randomDoubleWithExponent(-60, 80), randomShortDecimal])();
        inputs.push(String(x), x.toExponential(randomInt(21)), x.toPrecision(1 + randomInt(25)));
        if (Math.abs(x) < 1e21) inputs.push(x.toFixed(randomInt(30)));
    }
    for (let i = 0; i < scaled(120); ++i) {
        let text = pick(["", "", "+", "-"]) + randomDigits(randomInt(30));
        if (randomInt(2)) text += "." + randomDigits(randomInt(30));
        if (randomInt(2)) text += pick(["e", "E"]) + pick(["", "+", "-"]) + randomDigits(1 + randomInt(3));
        if (randomInt(4) === 0) text = pick([" ", "\n", " "]) + text + pick([" ", "\t", "﻿"]);
        inputs.push(text);
    }
    for (let i = 0; i < scaled(60); ++i) {
        const [prefix, alphabet] = pick([
            ["0x", "0123456789abcdefABCDEF"],
            ["0X", "0123456789abcdef"],
            ["0b", "01"],
            ["0B", "01"],
            ["0o", "01234567"],
            ["0O", "01234567"],
        ]);
        inputs.push(prefix + randomDigits(1 + randomInt(randomInt(3) ? 24 : 300), alphabet));
    }
    return inputs;
}

function stringToBigIntInputs() {
    const inputs = [
        "",
        " ",
        "0",
        "-0",
        "+0",
        "-",
        "+",
        " - ",
        "123",
        "-123",
        "+123",
        "  456  ",
        "1.0",
        "1.",
        ".1",
        "1e3",
        "0x10",
        "0X1F",
        "-0x10",
        "+0x10",
        "0b101",
        "0B11",
        "0o17",
        "0O17",
        "0x",
        "0b",
        "0o",
        "0xg",
        "0b2",
        "0o8",
        "1n",
        "Infinity",
        "12345678901234567890123456789",
        "-" + "9".repeat(50),
        "0x" + "fF".repeat(20),
        "　 77 ﻿",
        "1_000",
        "- 1",
        "+-1",
        "--1",
        "00012",
        "-00012",
        "١٢",
        "0x١",
        " 1 ",
        "1 2",
        "0x0",
        "0b0",
        "-0b1",
        "0o",
        "0o0",
        "0xF_F",
        "18446744073709551616",
        "-9223372036854775808",
    ];
    for (let i = 0; i < scaled(30); ++i) {
        const value = randomBigInt(160);
        inputs.push(value.toString(), pick(["", " ", "\n"]) + value.toString() + pick(["", " ", " "]));
        const magnitude = value < 0n ? -value : value;
        inputs.push("0x" + magnitude.toString(16), "0o" + magnitude.toString(8), "0b" + magnitude.toString(2));
    }
    return inputs;
}

function observeToIntegerOrInfinity(x) {
    // Array.prototype.indexOf converts fromIndex with ToIntegerOrInfinity and then asks HasProperty for that index,
    // counted from the end for negative values. Every double of magnitude 2^53 or more is already an integer.
    if (!Number.isNaN(x) && Math.abs(x) >= 2 ** 53 - 1) return x;
    const length = 2 ** 53 - 1;
    let key = null;
    const proxy = new Proxy(
        {},
        {
            get(target, property) {
                return property === "length" ? length : undefined;
            },
            has(target, property) {
                key = property;
                throw "found";
            },
        }
    );
    try {
        Array.prototype.indexOf.call(proxy, 0, x);
    } catch (error) {
        if (error !== "found") throw error;
    }
    const index = Number(key);
    return x <= -1 ? index - length : index;
}

function observeToIndex(x) {
    // ArrayBuffer's maxByteLength option goes through ToIndex. Values that are too large to reserve report the index
    // in the error message.
    try {
        return new ArrayBuffer(0, { maxByteLength: x }).maxByteLength;
    } catch (error) {
        const match = /^Not enough memory to allocate (\d+) bytes$/.exec(error.message);
        if (match) return Number(match[1]);
        if (error.message !== "Index must be a positive integer no greater than 2^53-1") throw error;
        return null;
    }
}

function integerConversionInputs() {
    const inputs = [...interestingDoubles, NaN, Infinity, -Infinity];
    for (const x of randomDoubles(scaled(260))) inputs.push(x);
    for (let i = 0; i < scaled(60); ++i)
        inputs.push(randomSign() * (randomInt(1024) + pick([0, 0.25, 0.5, 0.75, 0.5000001])));
    return inputs;
}

function lengthAndIndexInputs() {
    const inputs = [
        0,
        -0,
        0.5,
        -0.5,
        0.9999,
        -0.9999,
        1,
        -1,
        1.5,
        -1.5,
        12.7,
        -12.7,
        NaN,
        Infinity,
        -Infinity,
        2 ** 53 - 1,
        2 ** 53,
        2 ** 53 + 2,
        -(2 ** 53),
        2 ** 60,
        1e300,
        -1e300,
        5e-324,
        -5e-324,
        2 ** 45,
        2 ** 45 + 0.5,
        2 ** 52 + 0.5,
        2 ** 52 - 0.5,
        -(2 ** 52) - 0.5,
        Number.MAX_VALUE,
        -Number.MAX_VALUE,
    ];
    for (let i = 0; i < scaled(80); ++i) {
        // ToIndex is observed by reserving the index, so stay clear of sizes that the allocator might grant.
        if (randomInt(2)) inputs.push(randomSign() * (randomInt(1 << 20) + randomInt(8) / 8));
        else inputs.push(randomSign() * 2 ** (45 + randomInt(15)) * (1 + randomInt(1 << 20) / (1 << 20)));
    }
    return inputs;
}

print("//// FILE: value_conversions_table.rs");
printTableHeader();
print("");
emitTable(
    "STRING_TO_NUMBER",
    "(&str, u64)",
    stringToNumberInputs().map(text => [rustString(text), bitsOf(Number(text))])
);
emitTable(
    "STRING_TO_BIGINT",
    "(&str, Option<&str>)",
    stringToBigIntInputs().map(text => {
        let result;
        try {
            result = BigInt(text).toString();
        } catch (error) {
            if (!(error instanceof SyntaxError)) throw error;
            result = null;
        }
        return [rustString(text), rustOption(result, rustString)];
    })
);
emitTable(
    "INTEGER_CONVERSIONS",
    "(u64, i32, u32, i16, u16, i8, u8, u8)",
    integerConversionInputs().map(x => [
        bitsOf(x),
        x | 0,
        x >>> 0,
        new Int16Array([x])[0],
        new Uint16Array([x])[0],
        new Int8Array([x])[0],
        new Uint8Array([x])[0],
        new Uint8ClampedArray([x])[0],
    ])
);
emitTable(
    "INTEGER_LENGTH_AND_INDEX",
    "(u64, u64, u64, Option<u64>)",
    lengthAndIndexInputs().map(x => [
        bitsOf(x),
        bitsOf(observeToIntegerOrInfinity(x)),
        Array.prototype.push.call({ length: x }),
        rustOption(observeToIndex(x), String),
    ])
);

{
    const specials = [
        NaN,
        0,
        -0,
        Infinity,
        -Infinity,
        1,
        -1,
        0.5,
        -0.5,
        2,
        -3,
        1.5,
        -1.5,
        1e300,
        5e-324,
        2 ** 53 + 2,
        1.0000000000000002,
        0.9999999999999999,
    ];
    const rows = [];
    const exponentiate = (base, exponent) => base ** exponent;
    for (const base of specials) {
        for (const exponent of specials)
            rows.push([bitsOf(base), bitsOf(exponent), bitsOf(exponentiate(base, exponent))]);
    }
    for (let i = 0; i < scaled(100); ++i) {
        const base = pick([randomShortDecimal, () => randomDoubleWithExponent(-20, 20), randomFiniteDouble])();
        const exponent = pick([() => randomInt(60) - 30, randomShortDecimal, () => randomDoubleWithExponent(-10, 8)])();
        rows.push([bitsOf(base), bitsOf(exponent), bitsOf(exponentiate(base, exponent))]);
    }
    emitTable("NUMBER_EXPONENTIATE", "(u64, u64, u64)", rows);
}

// number_prototype_algorithms_table.rs

const finiteNumberInputs = () => [...interestingDoubles, ...randomDoubles(scaled(160))];

print("//// FILE: number_prototype_algorithms_table.rs");
printTableHeader();
print("");
{
    const rows = [];
    for (const x of [NaN, Infinity, -Infinity, ...finiteNumberInputs()]) {
        for (let round = 0; round < 2; ++round) {
            const radix = pick([2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 16, 17, 20, 25, 31, 32, 33, 35, 36]);
            const text = x.toString(radix);
            if (text.length <= 160 || rows.length % 16 === 0) rows.push([bitsOf(x), radix, rustString(text)]);
        }
    }
    for (const radix of [2, 3, 7, 16, 36]) {
        for (const x of [5e-324, 2 ** -1022, Number.MAX_VALUE, 0.1, 1 / 3, 2 ** 52 + 0.5])
            rows.push([bitsOf(x), radix, rustString(x.toString(radix))]);
    }
    emitTable("NUMBER_TO_STRING_WITH_RADIX", "(u64, u32, &str)", rows);
}
{
    const rows = [];
    const addToFixed = (x, fractionDigits) => {
        const text = x.toFixed(fractionDigits);
        if (Math.abs(x) < 1e21) {
            rows.push([bitsOf(x), fractionDigits, `Some(${rustString(text)})`]);
            return;
        }
        if (text !== String(x)) throw new Error(`toFixed of ${x} is not ToString`);
        rows.push([bitsOf(x), fractionDigits, "None"]);
    };
    for (const x of finiteNumberInputs())
        addToFixed(x, pick([0, 0, 1, 2, 2, 3, 5, 10, 17, 20, 25, 27, 28, 30, 50, 100, randomInt(101)]));
    for (const [x, fractionDigits] of [
        [0.5, 0],
        [1.5, 0],
        [2.5, 0],
        [-2.5, 0],
        [1.005, 2],
        [1.45, 1],
        [8.345, 2],
        [-0, 2],
        [-0.0000001, 2],
        [0.000001, 7],
        [123.456, 100],
        [5e-324, 100],
        [999999999999999999999, 3],
        [999999999999999900000, 3],
        [1e20 + 1, 2],
        [0.5, 100],
        [2 ** 52 + 0.5, 1],
        [2 ** 53, 27],
        [2 ** 53, 28],
        [1e-10, 27],
        [1e-10, 28],
    ]) {
        addToFixed(x, fractionDigits);
    }
    emitTable("NUMBER_TO_FIXED", "(u64, u32, Option<&str>)", rows);
}
{
    const rows = [];
    for (const x of finiteNumberInputs()) {
        rows.push([bitsOf(x), "None", rustString(x.toExponential())]);
        const fractionDigits = pick([0, 1, 2, 3, 5, 10, 15, 16, 17, 20, 30, 50, 100, randomInt(101)]);
        rows.push([bitsOf(x), `Some(${fractionDigits})`, rustString(x.toExponential(fractionDigits))]);
    }
    for (const x of [9.5, 9.95, 9.995, 0.00095, 99.5, 999.5, 2 ** 50 + 0.25, 2 ** 50 + 0.75, 2.2250738585072014e-308]) {
        for (const fractionDigits of [0, 1, 2, 3, 16, 17])
            rows.push([bitsOf(x), `Some(${fractionDigits})`, rustString(x.toExponential(fractionDigits))]);
    }
    emitTable("NUMBER_TO_EXPONENTIAL", "(u64, Option<u32>, &str)", rows);
}
{
    const rows = [];
    for (const x of finiteNumberInputs()) {
        for (let round = 0; round < 2; ++round) {
            const precision = pick([
                1,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                10,
                15,
                16,
                17,
                18,
                21,
                22,
                30,
                50,
                100,
                1 + randomInt(100),
            ]);
            rows.push([bitsOf(x), precision, rustString(x.toPrecision(precision))]);
        }
    }
    for (const x of [9.5, 9.95, 99.5, 0.000001, 0.0000001, 0.00000095, 123456, 1e21, 1e-7, 5e-324, 2 ** 50 + 0.25]) {
        for (const precision of [1, 2, 3, 6, 7, 17, 21, 22])
            rows.push([bitsOf(x), precision, rustString(x.toPrecision(precision))]);
    }
    emitTable("NUMBER_TO_PRECISION", "(u64, u32, &str)", rows);
}

// big_int_algorithms_table.rs

print("//// FILE: big_int_algorithms_table.rs");
printTableHeader();
print("");
{
    const values = [
        0n,
        1n,
        -1n,
        2n ** 53n - 1n,
        2n ** 53n,
        2n ** 53n + 1n,
        2n ** 53n + 2n,
        2n ** 53n + 3n,
        2n ** 54n + 2n,
        2n ** 54n + 6n,
        2n ** 54n + 1n,
        2n ** 64n - 1n,
        2n ** 1023n,
        (2n ** 53n - 1n) << 971n,
        ((2n ** 53n - 1n) << 971n) + 2n ** 970n - 1n,
        ((2n ** 53n - 1n) << 971n) + 2n ** 970n,
        2n ** 1024n,
        2n ** 1100n,
        ((2n ** 52n + 1n) << 100n) + (1n << 99n),
        ((2n ** 52n) << 100n) + (1n << 99n),
        ((2n ** 52n) << 100n) + (1n << 99n) + 1n,
    ];
    for (let i = 0; i < scaled(80); ++i) values.push(randomBigInt(randomInt(16) ? pick([60, 64, 100, 200]) : 1100));
    for (let i = 0; i < scaled(30); ++i) {
        const bits = 54n + BigInt(randomInt(randomInt(4) ? 200 : 1000));
        const base = (BigInt(randomInt(1 << 30)) | (1n << 52n)) << (bits - 53n);
        values.push(randomSign() < 0 ? -(base + (1n << (bits - 54n))) : base + (1n << (bits - 54n)));
    }
    const allValues = [...values, ...values.map(value => -value)];

    // Each value is converted with Number() and compared with doubles around it.
    const rows = [];
    const addRow = (value, doubles) => {
        const comparisons = doubles.map(x => `(${bitsOf(x)}, ${value < x ? "'<'" : value == x ? "'='" : "'>'"})`);
        rows.push([rustString(value.toString()), bitsOf(Number(value)), `&[${comparisons.join(", ")}]`]);
    };
    for (const value of allValues) {
        const x = Number(value);
        addRow(value, Number.isFinite(x) ? [x, nextDouble(x, 1), nextDouble(x, -1), x / 3] : [x, x / 3]);
    }
    for (const [value, doubles] of [
        [0n, [0, -0, 5e-324, -5e-324]],
        [-1n, [-0.5, -1.5]],
        [1n, [0.5, 1.5]],
        [5n, [Infinity, -Infinity]],
        [-5n, [Infinity, -Infinity]],
        [2n ** 2000n, [Infinity, Number.MAX_VALUE]],
        [3n, [3.0000000000000004]],
        [2n ** 53n + 1n, [2 ** 53, 2 ** 53 + 2]],
        [-(2n ** 64n), [-(2 ** 64)]],
        [10n ** 30n, [1e30]],
    ]) {
        addRow(value, doubles);
    }
    emitTable("BIGINT_TO_DOUBLE_AND_COMPARISONS", "(&str, u64, &[(u64, char)])", rows);

    const numbers = [...interestingDoubles, NaN, Infinity, -Infinity];
    for (let i = 0; i < scaled(40); ++i)
        numbers.push(
            randomSign() * Math.floor(randomFiniteDouble() % 1e30),
            Math.floor(randomDoubleWithExponent(0, randomInt(4) ? 200 : 1023))
        );
    emitTable(
        "NUMBER_TO_BIGINT",
        "(u64, &str)",
        numbers.map(x => [bitsOf(x), rustString(attempt(() => BigInt(x).toString()))])
    );

    const toStringRows = [];
    for (const value of [0n, -0n, 1n, -1n, 35n, -36n, 2n ** 64n, -(2n ** 64n) + 1n]) {
        for (const radix of [2, 3, 10, 16, 36])
            toStringRows.push([rustString(value.toString()), radix, rustString(value.toString(radix))]);
    }
    for (let i = 0; i < scaled(120); ++i) {
        const value = randomBigInt(pick([16, 64, 200, 500]));
        const radix = 2 + randomInt(35);
        toStringRows.push([rustString(value.toString()), radix, rustString(value.toString(radix))]);
    }
    emitTable("BIGINT_TO_STRING", "(&str, u32, &str)", toStringRows);

    const asIntNRows = [];
    const addAsIntN = (bits, value) =>
        asIntNRows.push([
            bits,
            rustString(value.toString()),
            rustString(attempt(() => BigInt.asIntN(bits, value).toString())),
            rustString(attempt(() => BigInt.asUintN(bits, value).toString())),
        ]);
    for (const bits of [0, 1, 2, 7, 8, 32, 59, 60, 61, 63, 64, 65, 120, 121]) {
        for (const value of [
            0n,
            1n,
            -1n,
            127n,
            128n,
            -128n,
            -129n,
            2n ** 63n,
            -(2n ** 63n),
            2n ** 64n - 1n,
            -(2n ** 64n),
            2n ** 60n,
            -(2n ** 60n),
            2n ** 120n - 1n,
            -(2n ** 120n),
        ]) {
            addAsIntN(bits, value);
        }
    }
    for (let i = 0; i < scaled(100); ++i) addAsIntN(randomInt(200), randomBigInt(pick([10, 64, 128, 250])));
    for (const value of [0n, 5n, -5n, 2n ** 100n, -(2n ** 100n)]) {
        for (const bits of [2 ** 31 - 1, 2 ** 31, 2 ** 40, 2 ** 53 - 1]) {
            if (value < 0n && bits === 2 ** 31 - 1) continue;
            addAsIntN(bits, value);
        }
    }
    emitTable("BIGINT_AS_INT_N_AND_AS_UINT_N", "(u64, &str, &str, &str)", asIntNRows);

    const shiftRows = [];
    const leftShift = (x, y) => x << y;
    const rightShift = (x, y) => x >> y;
    const addShift = (x, y) =>
        shiftRows.push([
            rustString(x.toString()),
            rustString(y.toString()),
            rustString(attempt(() => leftShift(x, y).toString())),
            rustString(attempt(() => rightShift(x, y).toString())),
        ]);
    const shiftValues = [0n, 1n, -1n, 5n, -5n, -4n, 2n ** 64n + 1n, -(2n ** 64n) - 1n, -(2n ** 64n)];
    for (const x of shiftValues) {
        for (const y of [
            0n,
            1n,
            -1n,
            2n,
            -2n,
            3n,
            31n,
            -31n,
            32n,
            63n,
            64n,
            65n,
            -63n,
            -64n,
            -65n,
            -100n,
            100n,
            2n ** 31n,
            -(2n ** 31n),
            3000000000n,
            -3000000000n,
            2n ** 32n - 1n,
            -(2n ** 32n - 1n),
            2n ** 32n,
            -(2n ** 32n),
            2n ** 70n,
        ]) {
            addShift(x, y);
        }
    }
    for (let i = 0; i < scaled(80); ++i) addShift(randomBigInt(pick([8, 64, 200])), BigInt(randomInt(300) - 150));
    emitTable("BIGINT_SHIFTS", "(&str, &str, &str, &str)", shiftRows);

    const exponentiationRows = [];
    const exponentiate = (base, exponent) => base ** exponent;
    const addExponentiation = (base, exponent) =>
        exponentiationRows.push([
            rustString(base.toString()),
            rustString(exponent.toString()),
            rustString(attempt(() => exponentiate(base, exponent).toString())),
        ]);
    for (const base of [0n, 1n, -1n, 2n, -2n, 3n, -3n, 10n, 2n ** 64n, -(2n ** 64n)]) {
        for (const exponent of [
            0n,
            1n,
            2n,
            3n,
            7n,
            8n,
            20n,
            -1n,
            -(2n ** 70n),
            2n ** 31n,
            3000000000n,
            2n ** 32n - 1n,
            2n ** 32n,
            2n ** 64n,
        ]) {
            addExponentiation(base, exponent);
        }
    }
    for (let i = 0; i < scaled(60); ++i) addExponentiation(randomBigInt(pick([4, 16, 64])), BigInt(randomInt(40)));
    emitTable("BIGINT_EXPONENTIATION", "(&str, &str, &str)", exponentiationRows);
}
