/*
 * Copyright (c) 2026-present, the Ladybird developers.
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

use crate::css_pixels::CssPixels;
use crate::display::FfiDisplay;
use std::ffi::c_void;

#[derive(Clone, Copy)]
#[repr(C)]
pub struct FfiLayoutBoxFacts {
    pub is_text_node: bool,
    pub is_break_node: bool,
    pub is_box: bool,
    pub is_block_container: bool,
    pub is_replaced_box: bool,
    pub is_replaced_box_with_children: bool,
    pub is_floating: bool,
    pub is_absolutely_positioned: bool,
    pub is_inline: bool,
    pub is_inline_block: bool,
    pub is_atomic_inline: bool,
    pub is_inline_node: bool,
    pub has_box_model_metrics: bool,
    pub is_fragmented_inline: bool,
    pub is_inline_flow_interrupting_block: bool,
    pub is_list_item_marker_box: bool,
    pub is_list_item_box: bool,
    pub is_svg_mask_box: bool,
    pub is_svg_clip_box: bool,
    pub is_replaced_element: bool,
    pub display_before_box_type_transformation_is_block_outside: bool,
    pub inline_axis_is_reverse: bool,
    pub has_dom_node: bool,
    pub children_are_inline: bool,
    pub is_anonymous: bool,
    pub can_have_children: bool,
    pub has_replaced_element_table_display_adjustment: bool,
    pub creates_block_formatting_context: bool,
    pub is_grid_item: bool,
    pub is_editing_host: bool,
    pub uses_button_layout: bool,
    pub may_reuse_precreated_used_values: bool,

    pub is_fieldset_box: bool,
    pub rendered_legend: *mut c_void,
    pub list_item_marker: *mut c_void,
    pub has_css_marker_content: bool,
    pub marker_content_inline_size: CssPixels,
    pub marker_content_block_size: CssPixels,
    pub marker_distance: CssPixels,
    pub marker_list_style_position: u8,

    pub has_definite_natural_width: bool,
    pub natural_width: CssPixels,
    pub has_definite_natural_height: bool,
    pub natural_height: CssPixels,
    pub has_definite_natural_aspect_ratio: bool,
    pub natural_aspect_ratio: f64,

    pub has_auto_content_width: bool,
    pub auto_content_width: CssPixels,
    pub has_auto_content_height: bool,
    pub auto_content_height: CssPixels,
    pub has_auto_content_aspect_ratio: bool,
    pub auto_content_aspect_ratio_numerator: CssPixels,
    pub auto_content_aspect_ratio_denominator: CssPixels,
    pub has_auto_content_box_size: bool,
    pub has_preferred_aspect_ratio: bool,
    pub preferred_aspect_ratio_numerator: CssPixels,
    pub preferred_aspect_ratio_denominator: CssPixels,
    pub has_default_preferred_width: bool,
    pub default_preferred_width: CssPixels,
    pub has_default_preferred_height: bool,
    pub default_preferred_height: CssPixels,
    pub initial_containing_block_inline_size: CssPixels,
    pub is_scroll_container: bool,

    pub has_layout_index: bool,
    pub layout_index: u32,
    pub display: FfiDisplay,
    pub is_svg_box: bool,
    pub is_svg_svg_box: bool,
    pub is_table_box: bool,
    pub is_table_wrapper: bool,
    pub is_table_row_group: bool,
    pub is_table_header_group: bool,
    pub is_table_footer_group: bool,
    pub is_table_row: bool,
    pub is_table_cell: bool,
    pub is_table_column_group: bool,
    pub is_table_column: bool,
    pub is_table_caption: bool,
    pub is_viewport: bool,

    pub document_in_quirks_mode: bool,
    pub is_in_user_agent_shadow_tree: bool,
    pub is_html_html_element: bool,
    pub is_html_body_element: bool,
}

impl Default for FfiLayoutBoxFacts {
    fn default() -> Self {
        Self {
            is_text_node: false,
            is_break_node: false,
            is_box: false,
            is_block_container: false,
            is_replaced_box: false,
            is_replaced_box_with_children: false,
            is_floating: false,
            is_absolutely_positioned: false,
            is_inline: false,
            is_inline_block: false,
            is_atomic_inline: false,
            is_inline_node: false,
            has_box_model_metrics: false,
            is_fragmented_inline: false,
            is_inline_flow_interrupting_block: false,
            is_list_item_marker_box: false,
            is_list_item_box: false,
            is_svg_mask_box: false,
            is_svg_clip_box: false,
            is_replaced_element: false,
            display_before_box_type_transformation_is_block_outside: false,
            inline_axis_is_reverse: false,
            has_dom_node: false,
            children_are_inline: false,
            is_anonymous: false,
            can_have_children: false,
            has_replaced_element_table_display_adjustment: false,
            creates_block_formatting_context: false,
            is_grid_item: false,
            is_editing_host: false,
            uses_button_layout: false,
            may_reuse_precreated_used_values: false,
            is_fieldset_box: false,
            rendered_legend: std::ptr::null_mut(),
            list_item_marker: std::ptr::null_mut(),
            has_css_marker_content: false,
            marker_content_inline_size: CssPixels::default(),
            marker_content_block_size: CssPixels::default(),
            marker_distance: CssPixels::default(),
            marker_list_style_position: 0,
            has_definite_natural_width: false,
            natural_width: CssPixels::default(),
            has_definite_natural_height: false,
            natural_height: CssPixels::default(),
            has_definite_natural_aspect_ratio: false,
            natural_aspect_ratio: 0.0,
            has_auto_content_width: false,
            auto_content_width: CssPixels::default(),
            has_auto_content_height: false,
            auto_content_height: CssPixels::default(),
            has_auto_content_aspect_ratio: false,
            auto_content_aspect_ratio_numerator: CssPixels::default(),
            auto_content_aspect_ratio_denominator: CssPixels::default(),
            has_auto_content_box_size: false,
            has_preferred_aspect_ratio: false,
            preferred_aspect_ratio_numerator: CssPixels::default(),
            preferred_aspect_ratio_denominator: CssPixels::default(),
            has_default_preferred_width: false,
            default_preferred_width: CssPixels::default(),
            has_default_preferred_height: false,
            default_preferred_height: CssPixels::default(),
            initial_containing_block_inline_size: CssPixels::default(),
            is_scroll_container: false,
            has_layout_index: false,
            layout_index: 0,
            display: FfiDisplay::block(),
            is_svg_box: false,
            is_svg_svg_box: false,
            is_table_box: false,
            is_table_wrapper: false,
            is_table_row_group: false,
            is_table_header_group: false,
            is_table_footer_group: false,
            is_table_row: false,
            is_table_cell: false,
            is_table_column_group: false,
            is_table_column: false,
            is_table_caption: false,
            is_viewport: false,
            document_in_quirks_mode: false,
            is_in_user_agent_shadow_tree: false,
            is_html_html_element: false,
            is_html_body_element: false,
        }
    }
}

pub type FfiLayoutNavCallback = unsafe extern "C" fn(context: *mut c_void, node: *mut c_void) -> *mut c_void;

#[derive(Clone, Copy)]
#[repr(C)]
pub struct FfiLayoutNavCallbacks {
    pub context: *mut c_void,
    pub parent: FfiLayoutNavCallback,
    pub first_child: FfiLayoutNavCallback,
    pub next_sibling: FfiLayoutNavCallback,
    pub previous_sibling: FfiLayoutNavCallback,
    pub containing_block: FfiLayoutNavCallback,
}
